### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by DanGdl** [Eden-Sheiko/Vet-program#1]
https://github.com/Eden-Sheiko/Vet-program/blob/1f93e73f686fbcc1c2a01a16e429bdc8529142e4/Animal.hpp#L55 -> what does this boolean value mean? explain it in method's docs

**Comment by Eden-Sheiko** [comment]
#  documentation was added to the following method:
` virtual bool check_health() = 0;`
/**
     * \brief check_health() Pure Virtual Function
     * each class (dog,cat,cow) inherits from class animal
     * and overrides this function for his own features
     * @return bool if the animal is sick or not
     * @see Dog.hpp
     * @see Cat.hpp
     * @see Cow.hpp
     */

**Comment by DanGdl** [comment]
But here https://github.com/Eden-Sheiko/Vet-program/blob/f8ec8412b8fcf9bb057f8993bc93ac1d51f66b3a/Vet.hpp#L50 you use it like true -> healthy, false -> sick. Fix documentation

**Comment by Eden-Sheiko** [comment]
fixed
